//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.03 at 12:51:13 PM CDT 
//


package com.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.0" />
 *       &lt;attribute name="folioDigital" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fechaAutenticacion" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="selloTitulo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="noCertificadoAutoridad" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="selloAutenticacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Autenticacion")
public class Autenticacion {

    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "folioDigital", required = true)
    protected String folioDigital;
    @XmlAttribute(name = "fechaAutenticacion", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaAutenticacion;
    @XmlAttribute(name = "selloTitulo", required = true)
    protected String selloTitulo;
    @XmlAttribute(name = "noCertificadoAutoridad", required = true)
    protected String noCertificadoAutoridad;
    @XmlAttribute(name = "selloAutenticacion", required = true)
    protected String selloAutenticacion;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the folioDigital property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolioDigital() {
        return folioDigital;
    }

    /**
     * Sets the value of the folioDigital property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolioDigital(String value) {
        this.folioDigital = value;
    }

    /**
     * Gets the value of the fechaAutenticacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaAutenticacion() {
        return fechaAutenticacion;
    }

    /**
     * Sets the value of the fechaAutenticacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaAutenticacion(XMLGregorianCalendar value) {
        this.fechaAutenticacion = value;
    }

    /**
     * Gets the value of the selloTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelloTitulo() {
        return selloTitulo;
    }

    /**
     * Sets the value of the selloTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelloTitulo(String value) {
        this.selloTitulo = value;
    }

    /**
     * Gets the value of the noCertificadoAutoridad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoCertificadoAutoridad() {
        return noCertificadoAutoridad;
    }

    /**
     * Sets the value of the noCertificadoAutoridad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoCertificadoAutoridad(String value) {
        this.noCertificadoAutoridad = value;
    }

    /**
     * Gets the value of the selloAutenticacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelloAutenticacion() {
        return selloAutenticacion;
    }

    /**
     * Sets the value of the selloAutenticacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelloAutenticacion(String value) {
        this.selloAutenticacion = value;
    }

}
