//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.03 at 12:53:26 PM CDT 
//


package com.jaxb.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TituloElectronico }
     * 
     */
    public TituloElectronico createTituloElectronico() {
        return new TituloElectronico();
    }

    /**
     * Create an instance of {@link TituloElectronico.FirmaResponsables }
     * 
     */
    public TituloElectronico.FirmaResponsables createTituloElectronicoFirmaResponsables() {
        return new TituloElectronico.FirmaResponsables();
    }

    /**
     * Create an instance of {@link TituloElectronico.Institucion }
     * 
     */
    public TituloElectronico.Institucion createTituloElectronicoInstitucion() {
        return new TituloElectronico.Institucion();
    }

    /**
     * Create an instance of {@link TituloElectronico.Carrera }
     * 
     */
    public TituloElectronico.Carrera createTituloElectronicoCarrera() {
        return new TituloElectronico.Carrera();
    }

    /**
     * Create an instance of {@link TituloElectronico.Profesionista }
     * 
     */
    public TituloElectronico.Profesionista createTituloElectronicoProfesionista() {
        return new TituloElectronico.Profesionista();
    }

    /**
     * Create an instance of {@link TituloElectronico.Expedicion }
     * 
     */
    public TituloElectronico.Expedicion createTituloElectronicoExpedicion() {
        return new TituloElectronico.Expedicion();
    }

    /**
     * Create an instance of {@link TituloElectronico.Antecedente }
     * 
     */
    public TituloElectronico.Antecedente createTituloElectronicoAntecedente() {
        return new TituloElectronico.Antecedente();
    }

    /**
     * Create an instance of {@link TituloElectronico.Autenticacion }
     * 
     */
    public TituloElectronico.Autenticacion createTituloElectronicoAutenticacion() {
        return new TituloElectronico.Autenticacion();
    }

    /**
     * Create an instance of {@link TituloElectronico.FirmaResponsables.FirmaResponsable }
     * 
     */
    public TituloElectronico.FirmaResponsables.FirmaResponsable createTituloElectronicoFirmaResponsablesFirmaResponsable() {
        return new TituloElectronico.FirmaResponsables.FirmaResponsable();
    }

}
